### Nonlinear Option Pricing, Master 2 Probabilités et Finance, Sorbonne Université and École polytechnique
# Homework III (mandatory: 30% of final grade)

### Due Date: 11:55 PM Tuesday, February 25, 2025
You should turn in the notebook on the Moodle course website.

Please comment your code properly.

Before you turn in the notebook, press the "Run all cells" button in the toolbar, and make sure all the calculation results and graphs are produced correctly in a reasonable time frame, and then save the notebook.

# Uncertain Mortality Model vs American Options

#### Re-insurance Deals

In this assignment, we study the *Uncertain Mortality Model* for the pricing of reinsurance deals. For the sake of simplicity, in this assignment we only consider one type of default: the risk of death.

We consider the following reinsurance product:

- At maturity, if the insurance subscriber is alive, the issuer delivers a put on the underlying $X$

$$
u^\textrm{mat}( x) = (K_\textrm{mat} - x)_+.
$$

- At the time of death, if it is before the maturity, the issuer delivers an exit payoff, typically another put on the underlying $X$.

$$
u^D(t, x) = (K_D - x)_+.
$$

- The subscriber pays a constant fee $α\Delta t$ at every time step until death or the maturity or the product

- The insurance sells a large number of these contracts to subscribers. We assume that the times of death of the subscribers $\tau^D$ are independent, and identically distributed, and also independent of the underlying's stock price.

- We assume that the underlying's risk neutral price dynamics is the Black-Scholes model with zero interest rate/repo/dividend yield

$$
dX_t = \sigma X_t d W_t.
$$

#### The Insurers' Approach and Risk-Neutral Pricing

This contract shows two types of risk: the times of death of the subscribers and the changes in the price of the underlying. 

In this case, the issuer can apply the insurer's approach to the risk of death times, i.e., the law of large numbers. The more people buy the contract, the less risk.

Choosing a risk-neutral measure under which the death times $\tau^D$ have the same distribution as under the historical probability measure is equivalent to applying the arbitrage-pricing approach to the financial risk insurer's rule on the risk of death. The price of the contract is then

$$
u(t, x) = \mathbb{E}^\mathbb{Q}_{t, x} \left[u^\textrm{mat}(X_T) \mathbb{1}_{\tau^D \geq T} -\int_t^T\alpha\mathbb{1}_{\tau^D>s}ds+ u^D(\tau^D, X_{\tau^D}) \mathbb{1}_{\tau^D < T} \right].
$$

#### Deterministic Death Rate

If the death intensity is a deterministic function $\lambda_t^D$ (i.e. $\tau^D$ has an exponential distribution with time-dependent intensity $\lambda_t^D$), then we have seen that $u$ is the solution to the linear PDE

$$
\left\{\begin{array}{l}
\partial_t u + \frac{1}{2} \sigma^2 x^2 \partial_x^2 u -\alpha + \lambda_t^D \cdot (u^D - u) = 0,\\
u(T, \cdot) \equiv u^\textrm{mat}.
\end{array}\right.
$$

#### Uncertain Mortality Model

If the death rate is uncertain, we assume that it is adapted (i.e., it does not look into the future) and belongs to a moving corridor
$\left[\underline{\lambda}_t, \overline{\lambda}_t\right]$. The most conservative way to price the contract is to compute the (financially) worst death rate process $\lambda_t^D$ as being chosen so as to maximize the value of the contract. The resulting HJB equation is

$$
\left\{\begin{array}{l}
\partial_t u + \frac{1}{2} \sigma^2 x^2 \partial^2_x u -\alpha + \Lambda^D(t, u^D - u) \cdot (u^D - u) = 0,\\
u(T, \cdot) \equiv u^\textrm{mat},
\end{array}\right.
$$
where the function $\Lambda^D$ is defined by
$$
\Lambda^D (t, y) = \left\{\begin{array}{l}
    \overline{\lambda}^D_t \quad \textrm{if} \ y \geq 0, \\
    \underline{\lambda}^D_t \quad \textrm{otherwise.}
\end{array}\right.
$$

## Link with $1$-BSDE and Numerical Schemes

From the Pardoux-Peng theorem, we know that the solution $u(0, x)$ can be represented as the solution $Y_0^x$ to the $1$-BSDE

$$
dY_t = -f(t, X_t, Y_t, Z_t) \, dt + Z_t \, dW_t,
$$

with the terminal condition $Y_T = u^\textrm{mat} (X_T)$, where $X_0 = x$ and

$$
f(t, x, y, z) = -\alpha + \Lambda^D(t, u^D(t, x) - y) \cdot (u^D(t, x) - y).
$$


## BSDE Discretization

### Explicit Euler Schemes

\begin{align*}
Y_{t_n} =& \ u^{\text{mat}}\left(X_{t_n}\right)\\
Y_{t_{i - 1}} =& \ \mathbb{E}^\mathbb{Q}_{i - 1} [ Y_{t_i} ] -\alpha\Delta t_i + \Lambda^D \left(t_{i - 1}, u^D(t_{i - 1} , X_{t_{i - 1}}) - \mathbb{E}^\mathbb{Q}_{i - 1} [ Y_{t_i} ]\right) \cdot \left( u^D(t_{i - 1}, X_{t_{i - 1}}) - \mathbb{E}^\mathbb{Q}_{i - 1} [ Y_{t_i} ] \right) \Delta t_i\\
=& -\alpha\Delta t_i + \left( \mathbb{E}^\mathbb{Q}_{i - 1} [ Y_{t_i} ] \left( 1 - \overline{\lambda}^D \Delta t_i \right) +
u^D(t_{i - 1}, X_{t_{i - 1}}) \overline{\lambda}^D \Delta t_i \right) \mathbb{1}_{u^D\left(t_{i - 1}, X_{t_{i - 1}}\right) \geq \mathbb{E}_{i-1}[Y_{t_i}]}\\
& + \left( \mathbb{E}^\mathbb{Q}_{i - 1} [ Y_{t_i} ] \left( 1 - \underline{\lambda}^D \Delta t_i \right) +
u^D(t_{i - 1}, X_{t_{i - 1}}) \underline{\lambda}^D \Delta t_i \right) \mathbb{1}_{u^D\left(t_{i - 1}, X_{t_{i - 1}}\right) < \mathbb{E}_{i-1}[Y_{t_i}]}.
\end{align*}

### Implicit Euler Scheme

\begin{align*}
Y_{t_n} =& \ u^{\text{mat}}\left(X_{t_n}\right)\\
Y_{t_{i - 1}} =& \ \mathbb{E}^\mathbb{Q}_{i - 1} [Y_{t_i}] -\alpha\Delta t_i+ \Lambda^D \left(t_{i - 1}, u^D(t_{i - 1}, X_{t_{i - 1}}) - Y_{t_{i - 1}}\right) \cdot \left( u^D(t_{i - 1}, X_{t_{i - 1}}) - Y_{t_{i - 1}} \right) \Delta t_i.
\end{align*}

The implicit scheme involves $Y_{t_{i - 1}}$ on both sides of the equation, which generally requires a root-finding routine to find $Y_{t_{i - 1}}$. However in this specific case, it can be shown that 

\begin{equation}u^D(t_{i-1}, X_{t_{i-1}}) \geq Y_{t_{i-1}}\quad\text{if and only if}\quad u^D(t_{i-1}, X_{t_{i-1}}) \geq \mathbb{E}^{\mathbb{Q}}_{i-1}\left[Y_{t_i}\right]-\alpha\Delta t_i.\end{equation}

Thus

\begin{split}
Y_{t_{i - 1}} =& \frac{1}{1 + \overline{\lambda}^D \Delta t_i} \left( \mathbb{E}^\mathbb{Q}_{i - 1} [ Y_{t_i} ] - \alpha\Delta t_i +
u^D(t_{i - 1}, X_{t_{i - 1}}) \overline{\lambda}^D \Delta t_i \right) \mathbb{1}_{u^D\left(t_{i - 1}, X_{t_{i - 1}}\right) \geq \mathbb{E}_{i-1}[Y_{t_i}]-\alpha\Delta t_i}\\
& + \frac{1}{1 + \underline{\lambda}^D \Delta t_i} \left( \mathbb{E}^\mathbb{Q}_{i - 1} [ Y_{t_i} ] -\alpha\Delta t_i +
u^D(t_{i - 1}, X_{t_{i - 1}}) \underline{\lambda}^D \Delta t_i \right) \mathbb{1}_{u^D(t_{i - 1}, X_{t_{i - 1}}) < \mathbb{E}_{i-1}[Y_{t_i}]-\alpha\Delta t_i}.
\end{split}



In [3]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import norm
import seaborn as sns
import matplotlib as mpl

In [58]:
def blackscholes_mc(S=100, vol=0.2, r=0, q=0, ts=np.linspace(0, 1, 13), npaths=10):
    """Generate Monte-Carlo paths in Black-Scholes model.

    Parameters
    ----------
    S: scalar
        The spot price of the underlying security.
    vol: scalar
        The implied Black-Scholes volatility.
    r: scalar
        The annualized risk-free interest rate, continuously compounded.
    q: scalar
        The annualized continuous dividend yield.
    ts: array_like
        The time steps of the simualtion
    npaths: int
        the number of paths to simulate

    Returns
    -------
    paths: ndarray
        The Monte-Carlo paths.
    """
    nsteps = len(ts) - 1
    ts = np.asfarray(ts)[:, np.newaxis]
    W = np.cumsum(np.vstack((np.zeros((1, npaths), dtype=np.float64),
                             np.random.randn(nsteps, npaths) * np.sqrt(np.diff(ts, axis=0)))),
                  axis=0)
    paths = np.exp(-0.5*vol**2*ts + vol*W)*S*np.exp((r-q)*ts)
    return paths

def blackscholes_price(K, T, S, vol, r=0, q=0, callput='call'):
    """Compute the call/put option price in the Black-Scholes model
    
    Parameters
    ----------
    K: scalar or array_like
        The strike of the option.
    T: scalar or array_like
        The maturity of the option, expressed in years (e.g. 0.25 for 3-month and 2 for 2 years)
    S: scalar or array_like
        The current price of the underlying asset.
    vol: scalar or array_like
        The implied Black-Scholes volatility.
    r: scalar or array_like
        The annualized risk-free interest rate, continuously compounded.
    q: scalar or array_like
        The annualized continuous dividend yield.
    callput: str
        Must be either 'call' or 'put'.

    Returns
    -------
    price: scalar or array_like
        The price of the option.

    Examples
    --------
    >>> blackscholes_price(95, 0.25, 100, 0.2, r=0.05, callput='put')
    1.5342604771222823
    """
    F = S*np.exp((r-q)*T)
    v = np.sqrt(vol**2*T)
    d1 = np.log(F/K)/v + 0.5*v
    d2 = d1 - v
    try:
        opttype = {'call':1, 'put':-1}[callput.lower()]
    except:
        raise ValueError('The value of callput must be either "call" or "put".')
    price = opttype*(F*norm.cdf(opttype*d1)-K*norm.cdf(opttype*d2))*np.exp(-r*T)
    return price


def pwlinear_basis(xknots):
    """Basis that represent a piecewise linear function with given knots"""
    fs = [lambda x: np.ones_like(x, dtype=np.float64), lambda x: x-xknots[0]]
    fs.extend([lambda x, a=xknots[i]: np.maximum(x-a, 0) for i in range(len(xknots))])
    return fs


def pwlinear_fit(xdata, ydata, xknots):
    """Fit a piecewise linear function with xknots to xdata and ydata"""
    fs = pwlinear_basis(xknots)
    A = np.vstack([f(xdata) for f in fs]).T
    ps = np.linalg.lstsq(A, ydata, rcond=None)[0]
    return ps, fs

<b>Note.</b> To be more specific about the payouts of the product, we make the following assumptions:

- We assume that all transactions occur at the end of the month, i.e. the insurance subsriber is expected to pay a fee of $\alpha/12$ at the end of each month; if the subscriber dies in the middle of the month, the death payment will be made at the end of that month. 

- If the death occurs at the maturity, we assume that the death comes first and the death payment $u^D$ will be made.

## Assignment III

<b style="color:darkorange">Question 1</b> (Deterministic Mortality Rate Model)

We assume that the underlying's risk neutral price dynamics is the Black-Scholes model with zero interest rate/repo/dividend yield

$$dX_t = \sigma X_t d W_t,\quad X_0=100,\quad\sigma=0.3$$

We shall price the reinsurance deal using two Monte Carlo methods explained below.

<b>(a).</b> (Direct simulation of death times) Implement a Monte Carlo simulation by directly simulating death time $\tau^D$ for each path to estimate the quantity

$$u(t, x) = \mathbb{E}^\mathbb{Q}_{t, x} \left[u^\textrm{mat}(X_T) \mathbb{1}_{\tau^D \geq T} - \int_t^T\alpha \mathbb{1}_{\tau^D> s}ds
+ u^D(\tau^D, X_{\tau^D}) \mathbb{1}_{\tau^D < T} \right],$$

when $T=10$, $K_{\text{mat}}=90$, $K_D=100$, $\alpha=3$, and $\tau^D$ has an exponential distribution of constant intensity $\lambda^D=0.025$. Use monthly time steps.

<b>(b).</b> (Averaing over death events) Using the Feynman-Kac formula, derive a stochastic representation of the linear PDE 

$$\left\{\begin{array}{l}\partial_t u + \frac{1}{2}\sigma^2 x^2 \partial_x^2 u - \alpha + \lambda^D \cdot (u^D - u) = 0\\
        u(T, x) \equiv u^\textrm{mat}(x)\end{array}\right.$$
        
that does not involve simulating death times $\tau^D$. Explain how one can get this stochastic representation from the one given in (a). Implement the corresponding Monte Carlo simulation to estimate $u(0,X_0)$.

<b style="color:red">Warning: during this project i considered that T=10 mean that the time of study is of ten years , and that every month we pay alpha/12

In [90]:
sns.set_style("whitegrid")
mpl.rcParams['figure.dpi'] = 100
params_grid = {"color": 'lightgrey', "linestyle": 'dotted', "linewidth": 0.7 }
# note that lambda is a reserved keyword in python, so we use lambd instead

def exponential_samples(n, lambd):# mean equal to 1/lambda
    """Generate n samples from exponential distribution with rate lambd"""
    return -np.log(np.random.rand(n))/lambd

T=10 #10 months or 10 years?
K_D=100
K_mat=90
alpha=3
lambd=0.025 #mean time of death is 40 months
S=100
vol=0.3
r=0
q=0
npaths=1000
ts = np.linspace(0, T, int(np.round(T*12))+1)
dt=ts[1]-ts[0]

def u_mat(x):
    return np.maximum(K_mat - x, 0)

def u_D(x):
    return np.maximum(K_D - x, 0)

<b style="color:green">Question a</b> (Direct simulation of death times)

In [82]:
def bonding_indices(x, L):
    if x<=L[0] :return L[0]
    if x>L[-1] :return L[-1]
    for i in range(len(L)-1):
        if L[i] < x <= L[i+1]:
            return L[i+1]
    

In [86]:
#ts=np.linspace(0, T*12, T*12+1)
paths=blackscholes_mc(S, vol, r, q, ts, npaths)
stoping_times=(exponential_samples(npaths, lambd))
pathf=paths[-1]


#pathi=np.array([paths[:,i][min(int(stoping_times[i])+1,T*12)] for i in range(len(stoping_times))])
pathi=np.array([bonding_indices(stoping_times[i], paths[:,i]) for i in range(len(stoping_times))])
finalv = np.where(T>= stoping_times, u_D(pathi)-alpha*stoping_times, u_mat(pathf)-alpha*T)

#pathi=np.array([paths[:,i][min(int(stoping_times[i])+1,T)] for i in range(len(stoping_times))])
#finalv = np.where(T*12 >= stoping_times, u_D(pathi)-alpha/12*stoping_times, u_mat(pathf)-alpha*T)
print("the price of the reinsurance deal", np.mean(finalv))


the price of the reinsurance deal 20.965444738877846


<b style="color:green">Question b</b> (Averaing over death events) deriving a stochastic representation of the linear PDE 

The Feynman-Kac formula shows that the solution of the eqaution  $$\left\{\begin{array}{l}\partial_t u + \frac{1}{2}\sigma^2 x^2 \partial_x^2 u - \alpha + \lambda^D \cdot (u^D - u) = 0\\
        u(T, x) \equiv u^\textrm{mat}(x)\end{array}\right.$$
is given by $$u(t, x) = \mathbb{E}^\mathbb{Q}_{t, x} \left[ e^{-\int_t^T \lambda_D \, ds}  u_{\text{mat}}(X_T)+ \int_t^T e^{-\int_t^s{\lambda_D}dv}(-\alpha + u^D(s, X_{s}) )ds \right],$$

Using the fact that the death times are the first jump times of independent Poisson processes with  deterministic intensities $\lambda^D$, and independent of $X_{t}:$




$$u(t, x) = \mathbb{E}^\mathbb{Q}_{t, x} \left[u^\textrm{mat}(X_T) \mathbb{1}_{\tau^D \geq T} - \int_t^T\alpha \mathbb{1}_{\tau^D> s}ds
+ u^D(\tau^D, X_{\tau^D}) \mathbb{1}_{\tau^D < T} \right],$$


$$
= \mathbb{E}^{Q}_{t,x} \left[ u_{\text{mat}}(X_T) 1_{\tau_D \geq T}  \right] - \mathbb{E}^{Q}_{t,x} \left[\int_t^T \alpha 1_{\tau_D \geq s} \, ds\right]

+ \mathbb{E}^{Q}_{t,x} \left[ u_D(\tau_D, X_{\tau_D}) 1_{\tau_D < T}  \right]
$$
we have:
$$
\mathbb{E}^{Q}_{t,x} \left[ u_{\text{mat}}(X_T) 1_{\tau_D \geq T}  \right] = e^{-\int_t^T \lambda_D \, ds} \mathbb{E}^{Q}_{t,x} \left[ u_{\text{mat}}(X_T) \right]
$$

$$
\mathbb{E}^{Q}_{t,x} \left[  \int_t^T \alpha 1_{\tau_D \geq s}  \, ds \right] = \alpha \int_t^T e^{-\int_t^s \lambda_D \, dv} \, ds 
$$

$$
\mathbb{E}^{Q}_{t,x} \left[ u_D(\tau_D, X_{\tau_D}) 1_{\tau_D < T}  \right] = \mathbb{E}^{Q}_{t,x} \left[ \int_t^T u_D(s, X_s) \lambda_D e^{-\int_t^s \lambda_D(v) \, dv} \, ds \right]
$$

this imply: 
$$u(t, x) = \mathbb{E}^\mathbb{Q}_{t, x} \left[ e^{-\int_t^T \lambda^D \, ds}  u_{\text{mat}}(X_T)+ \int_t^T e^{-\int_t^s({\lambda^D})dv}(-\alpha +\lambda_D u^D(s, X_{s}) )ds \right],$$

Implement the corresponding Monte Carlo simulation to estimate $ u(0,X_0)$.

$$u(t, x) = \mathbb{E}^\mathbb{Q}_{t, x} \left[ e^{-(T-t) \lambda^D}  u_{\text{mat}}(X_T)+ \int_t^T e^{-(s-t){\lambda^D}}(-\alpha +\lambda_D \ u^D(s, X_{s}) )ds \right],$$

In [87]:
#g=lambda x,s,t: np.exp(-(s-t)*lambd) * (-alpha/12 +lambd*max(0,K_D-x)) 
g=lambda x,s,t: np.exp(-(s-t)*lambd) * (-alpha +lambd*max(0,K_D-x)) 
h=lambda T,t,x: np.exp(-(T-t)*lambd) * u_mat(x)
def payoff(path):
    dt=ts[1]-ts[0]
    s=0
    for i in range(len(path)-1):
        #s+=g(path[i],i,0)  
        s+=g(path[i],i*dt,0)*dt
    #s+=h(12*T,0,path[-1])
    s+=h(T,0,path[-1])
    return s

print("The price of the reinsurance deal using 'Averaing over death events' method:", np.mean([payoff(path) for path in np.transpose(paths)]))


The price of the reinsurance deal using 'Averaing over death events' method: 21.03647818127272


<b style="color:darkorange">Question 2</b> (Uncertain Mortality Rate Model - BSDE)

Assume that $\lambda^D_t \in \left[\underline{\lambda}^D, \overline{\lambda}^D \right]$, where $\underline{\lambda}^D=0.005$ and $\overline{\lambda}^D=0.04$.

<b>(a).</b> Implement the implicit Euler scheme for BSDE. Use piecewise-linear fit with 10 knots to estimate the conditional expectation $\mathbb{E}^{\mathbb{Q}}_{i-1}\left[Y_{t_i}\right]$. Use the numpy function percentile to define the minimum and maximum knots. Use the percentiles 1 and 99 percent. Use 100,000 paths.

<b>(b).</b> Run an independent new simuation. Use the estimates of $\mathbb{E}^{\mathbb{Q}}_{i-1}\left[Y_{t_i}\right]$ obtained in (a) to get a lower bound estimate.

<b>(c).</b> How does the price compare with the price in the model with deterministic mortality rate $\underline{\lambda}^D$? with deterministic mortality rate $\overline{\lambda}^D$? Check numerically.

The HJB equation is : $$\left\{\begin{array}{l}\partial_t u + \frac{1}{2}\sigma^2 x^2 \partial_x^2 u - \alpha + \Lambda_D(t, u_D - u) (u_D - u) = 0\\
        u(T, x) \equiv u^\textrm{mat}(x)\end{array}\right.$$


$$
\Lambda_D(t, y) = 
\begin{cases}
\overline{\lambda}^D & \text{if } y \geq 0 \\
\underline{\lambda}^D, & \text{otherwise}
\end{cases}
$$

\begin{split}
Y_{t_{i - 1}} =& \frac{1}{1 + \overline{\lambda}^D \Delta t_i} \left( \mathbb{E}^\mathbb{Q}_{i - 1} [ Y_{t_i} ] - \alpha\Delta t_i +
u^D(t_{i - 1}, X_{t_{i - 1}}) \overline{\lambda}^D \Delta t_i \right) \mathbb{1}_{u^D\left(t_{i - 1}, X_{t_{i - 1}}\right) \geq \mathbb{E}_{i-1}[Y_{t_i}]-\alpha\Delta t_i}\\
& + \frac{1}{1 + \underline{\lambda}^D \Delta t_i} \left( \mathbb{E}^\mathbb{Q}_{i - 1} [ Y_{t_i} ] -\alpha\Delta t_i +
u^D(t_{i - 1}, X_{t_{i - 1}}) \underline{\lambda}^D \Delta t_i \right) \mathbb{1}_{u^D(t_{i - 1}, X_{t_{i - 1}}) < \mathbb{E}_{i-1}[Y_{t_i}]-\alpha\Delta t_i}.
\end{split}

$$Y_{t_n} = \ u^{\text{mat}}\left(X_{t_n}\right)$$

<b style="color:yellow">Question a</b> Implementing the implicit Euler scheme for BSDE. Using piecewise-linear fit with 10 knots to estimate the conditional expectation

In [117]:
lambda_max = 0.04
lambda_min = 0.005


def expected(ydata, xdata):
    x1 = np.percentile(xdata, 1)
    x2 = np.percentile(xdata, 99)
    xknots = np.linspace(x1, x2, 10)
    ps, fs = pwlinear_fit(xdata, ydata, xknots)
    return ps, fs

def calculate_Y(xdata, ydata):
    ps, fs = expected(ydata, xdata)
    E = np.vstack([f(xdata) for f in fs]).T @ ps - alpha * dt

    Y = np.where(u_D(xdata) >= E, 
             (1 / (1 + lambda_max * dt)) * (E + u_D(xdata) * lambda_max * dt),
             (1 / (1 + lambda_min * dt)) * (E + u_D(xdata) * lambda_min * dt))

    return Y, ps, fs


X = blackscholes_mc(S, vol, r, q, ts, npaths)
Y= u_mat(X[-1])

betas = np.zeros((len(ts)-1, 12))
functions = [None] * (len(ts)-1)

for i in range(len(ts)-2, -1, -1):
    Y, betas[i], functions[i] = calculate_Y(X[i],Y)



<b style="color:yellow">Question b</b> Runing an independent new simuation to get a lower bound estimate.

In [118]:
def calculate_Y2(xdata,i):
    E = np.vstack([f(xdata) for f in functions[i]]).T @ betas[i] - alpha * dt
    Y = np.where(u_D(xdata) >= E, 
             (1 / (1 + lambda_max * dt)) * (E + u_D(xdata) * lambda_max * dt),
             (1 / (1 + lambda_min * dt)) * (E + u_D(xdata) * lambda_min * dt))

    return Y

X = blackscholes_mc(S, vol, r, q, ts, npaths)
Y=u_mat(X[-1])



for i in range(len(ts)-2, -1, -1):
    Y= calculate_Y2(X[i],i)
    print(Y[2:6])
print("lower bound estimate", Y[0])

[89.1959799  89.56390984 89.55988856 89.44368531]
[88.42070127 88.91298538 88.90894723 88.81200293]
[87.49711801 87.81713574 87.81478754 87.76746914]
[87.20113487 87.51611602 87.51366289 87.46558719]
[86.77575202 87.17475766 87.16903909 87.11503708]
[86.5835543  87.08449666 87.07631316 87.02344788]
[86.03520465 86.8620891  86.85828559 86.81106462]
[86.12755543 86.66380815 86.65799094 86.60146436]
[85.32880318 86.06715338 86.06157437 86.02918416]
[85.50786596 85.9793679  85.97193576 85.95047402]
[85.10700742 85.61168981 85.60142225 85.59005495]
[85.01184725 85.50433678 85.49571258 85.47644232]
[84.29518022 85.06479168 85.05483323 85.03934325]
[83.87451086 84.57492604 84.56201825 84.55227809]
[83.45736976 84.14445763 84.12737084 84.13218699]
[83.16852679 83.90924364 83.89723795 83.90082846]
[82.84971121 83.47229956 83.45965261 83.46502931]
[82.65328058 83.2546267  83.24078521 83.24538977]
[82.08109701 82.83287775 82.8178192  82.82205032]
[81.88958219 82.49857778 82.48171725 82.48904956]


In [317]:
def BSDE():
    X = blackscholes_mc(S, vol, r, q, ts, npaths)
    Y= u_mat(X[-1])
    betas = np.zeros((len(ts), 12))
    functions = [None] * len(ts)

    for i in range(T*12-1, -1, -1):
        Y, betas[i], functions[i] = calculate_Y(X[i],Y)

####
    X = blackscholes_mc(S=S, vol=vol, r=r, q=q, ts=ts, npaths=npaths)
    Y=u_mat(X[-1])
    for i in range(T*12-1, -1, -1):
        Y= calculate_Y2(X[i],i)
    return Y[0]


<b style="color:yellow">Question c</b>  How does the price compare with the price in the model with deterministic mortality rate $\underline{\lambda}^D$ and $\overline{\lambda}^D$? Check numerically.

In [293]:
for _ in [lambda_max,lambda_min]:
    lambd=_
    ts=np.linspace(0, T*12, T*12+1)
    paths=blackscholes_mc(S, vol, r, q, ts, npaths)
    stoping_times=(exponential_samples(npaths, lambd))
    pathf=paths[-1]
    pathi=np.array([paths[:,i][min(int(stoping_times[i])+1,T*12)] for i in range(len(stoping_times))])
    finalv = np.where(T*12 >= stoping_times, u_D(pathi)-alpha/12*stoping_times, u_mat(pathf)-alpha*T*12)
    if _==lambda_max:
        print("the price of the reinsurance deal with deterministic mortality rate lambda_max:", np.mean(finalv))
    else:
        print("the price of the reinsurance deal with deterministic mortality rate lambda_min:", np.mean(finalv))

the price of the reinsurance deal with deterministic mortality rate lambda_max: 47.02977246000064
the price of the reinsurance deal with deterministic mortality rate lambda_min: 57.07061247304369


In [113]:
for _ in [lambda_max,lambda_min]:
    lambd=_
    ts=np.linspace(0, T*12, T*12+1)
    paths=blackscholes_mc(S, vol, r, q, ts, npaths)
    stoping_times=(exponential_samples(npaths, lambd))
    pathf=paths[-1]
    pathi=np.array([bonding_indices(stoping_times[i], paths[:,i]) for i in range(len(stoping_times))])
    finalv = np.where(T>= stoping_times, u_D(pathi)-alpha*stoping_times, u_mat(pathf)-alpha*T)
    if _==lambda_max:
        print("the price of the reinsurance deal with deterministic mortality rate lambda_max:", np.mean(finalv))
    else:
        print("the price of the reinsurance deal with deterministic mortality rate lambda_min:", np.mean(finalv))

the price of the reinsurance deal with deterministic mortality rate lambda_max: 29.445241810933968
the price of the reinsurance deal with deterministic mortality rate lambda_min: 47.200882706597724


 The price found in question 2b) should be higher than both the prices when $\lambda$ is constant, indeed it is the case 

<b style="color:darkorange">Question 3</b> (Uncertain Mortality Rate Model - Longstaff and Schwartz) In addition to the BSDE simulation, the reinsurance deals can be priced by adapting the Longstaff-Schwartz algorithm. An implementation of the Longstaff-Schwartz algorithm is provided below for your convenience.

The same lower and upper bounds of $\lambda_t^D$ are used as Question 2.

<b>(a).</b> In the example code, we use European put price (the strike is taken to be the average of $K_{\text{mat}}$ and $K_D$) and constant as basis functions to estimate the sum of future payoffs. Modify the code by using the piecewise-linear fit to estimate the sum of future payoffs.

<b>(b).</b> Compare the BSDE scheme with the Longstaff-Schwartz-like scheme in terms of variance. For each method run the two-step procedure (regression and indedenpent pricing) 20 times to estimate variance. Use 5000 paths for regression and 50000 for indepedent pricing.

<b>(c).</b> What is approximately the value of the fee $\alpha$ that makes the deal costless at inception?

<b style="color:pink">Question c</b> Longstaff-Schwartz algorithm for Uncertain Mortality Rate Model

In [291]:

S = 100
vol = 0.3
T = 10
#ts = np.linspace(0, T, int(np.round(T*12))+1)
ts=np.linspace(0, T*12, T*12+1)
alpha = 3/12
lambda_min = 0.005
lambda_max = 0.04

K_mat = 90.0
K_D = 100.0

def u_mat(x):
    return np.maximum(K_mat - x, 0)

def u_D(x):
    return np.maximum(K_D - x, 0)


# first Monte Carlo run to estimate the value function by regressions
npaths = 5000
paths = blackscholes_mc(S=S, vol=vol, r=0, q=0, ts=ts, npaths=npaths)
betas = np.zeros((len(ts), 2))
V = u_mat(paths[-1])
lambd = np.where(u_D(paths[-1]) >= V, lambda_max, lambda_min)
K = 0.5*(K_mat+K_D)
for i in range(len(ts)-2, 0, -1):
    #dt = ts[i+1]-ts[i]
    dt=1
    p = 1-np.exp(-lambd*dt)
    V = p*u_D(paths[i+1]) + (1-p)*V - alpha*dt
    Z = blackscholes_price(K, ts[-1]-ts[i], paths[i], vol, callput='put')
    A = np.vstack((np.ones_like(Z), Z)).T
    betas[i] = np.linalg.lstsq(A, V, rcond=None)[0]
    lambd = np.where(u_D(paths[i]) >= betas[i, 0]+betas[i, 1]*Z, lambda_max, lambda_min)

# independent simulation to obtain a lower bound
npaths = 100000
paths = blackscholes_mc(S=S, vol=vol, r=0, q=0, ts=ts, npaths=npaths)
V = u_mat(paths[-1])
lambd = np.where(u_D(paths[-1]) >= V, lambda_max, lambda_min)
K = 0.5*(K_mat+K_D)
for i in range(len(ts)-2, -1, -1):
    #dt = ts[i+1]-ts[i]
    dt=1
    p = 1-np.exp(-lambd*dt)
    V = p*u_D(paths[i+1]) + (1-p)*V - alpha*dt
    Z = blackscholes_price(K, ts[-1]-ts[i], paths[i], vol, callput='put')
    lambd = np.where(u_D(paths[i]) >= betas[i, 0]+betas[i, 1]*Z, lambda_max, lambda_min)
np.mean(V)

62.81344290342639

In [333]:

def princing_longstaff(alpha):
    # longstaff schwartz piecewise
    betas = np.zeros((len(ts), 12))
    functions = [None] * len(ts)
    npaths = 5000
    paths = blackscholes_mc(S=S, vol=vol, r=0, q=0, ts=ts, npaths=npaths)
    V = u_mat(paths[-1])
    lambd = np.where(u_D(paths[-1]) >= V, lambda_max, lambda_min)
    K = 0.5*(K_mat+K_D)
    for i in range(len(ts)-2, 0, -1):
        dt = ts[i+1]-ts[i]
        p = 1-np.exp(-lambd*dt)
        V = p*u_D(paths[i+1]) + (1-p)*V - alpha*dt #valeur future je pense (equivakent à l'actualisation des payoff optimale futur en americaine )
        betas[i], functions[i] =expected(V, paths[i])#expected(ydata, xdata)
        lambd = np.where(u_D(paths[i]) >= np.vstack([f(paths[i]) for f in functions[i]]).T @ betas[i], lambda_max, lambda_min)



    # independent simulation longstaff schwartz piecewise
    npaths = 50000
    paths = blackscholes_mc(S=S, vol=vol, r=0, q=0, ts=ts, npaths=npaths)
    V = u_mat(paths[-1])
    lambd = np.where(u_D(paths[-1]) >= V, lambda_max, lambda_min)
    K = 0.5*(K_mat+K_D)
    for i in range(len(ts)-2, -1, -1):
        dt = ts[i+1]-ts[i]
        p = 1-np.exp(-lambd*dt)
        V = p*u_D(paths[i+1]) + (1-p)*V - alpha*dt
        
        if i!=0: lambd = np.where(u_D(paths[i]) >= np.vstack([f(paths[i]) for f in functions[i]]).T @ betas[i], lambda_max, lambda_min)
    
    return np.mean(V)


<b style="color:pink">Question b</b> comparing the BSDE scheme with the Longstaff-Schwartz-like scheme

In [313]:
def princing_BSDE():
    X = blackscholes_mc(S=S, vol=vol, r=r, q=q, ts=ts, npaths=npaths)
    Y= u_mat(X[-1])

    betas = np.zeros((len(ts), 12))
    functions = [None] * len(ts)

    for i in range(T*12-1, -1, -1):
        Y, betas[i], functions[i] = calculate_Y(X[i],Y)

    X = blackscholes_mc(S=S, vol=vol, r=r, q=q, ts=ts, npaths=npaths)
    Y=u_mat(X[-1])
    for i in range(T*12-1, -1, -1):
        Y= calculate_Y2(X[i],i)
    return Y[0]

In [318]:
V_BSDE=[BSDE() for i in range(20)]

In [344]:
V_longstaff=[princing_longstaff() for i in range(20)]



TypeError: princing_longstaff() missing 1 required positional argument: 'alpha'

In [331]:
print(np.var(V_longstaff))
print(np.mean(V_longstaff))

0.005859308875093518
62.71971881124095


In [332]:
print(np.var(V_BSDE))
print(np.mean(V_BSDE))

2.0194839173657902e-28
64.61931923606794


<b style="color:yellow">Question c</b>  What is approximately the value of the fee $\alpha$ that makes the deal costless at inception?

<b style="color:pink">Question c</b> The value of the fee alpha that makes the deal costless at inception
We can use a gradient descent method to find the alpha that makes the deal costless

In [339]:
import numpy as np


# Approximation numérique de la dérivée (différences finies centrées)
def numerical_derivative(f, x, h=1e-5):
    return (f(x + h) - f(x - h)) / (2 * h)

# Implémentation de Newton-Raphson
def newton_raphson(f, x0, tol=1e-6, max_iter=10, h=1e-5):
    x = x0
    for _ in range(max_iter):
        fx = f(x)
        dfx = numerical_derivative(f, x, h)
        """
        if abs(fx) < tol:  # Condition de convergence
            return x
        
        if abs(dfx) < 1e-10:  # Éviter la division par zéro
            print("La dérivée est trop proche de zéro. L'algorithme s'arrête.")
            return None"""

        x -= fx / dfx  # Mise à jour de Newton-Raphson
    
    
    return x

# Paramètres de recherche
x0 = 3  # Point de départ

# Exécution
root = newton_raphson(princing_longstaff, x0)




In [362]:
alphap=225.56/(12*10)

In [363]:
princing_longstaff(alphap)

0.07475718131590513

<b style="color:darkorange">Question 4.</b> Set $K_D=0$, and all the other parameters remain the same, in particualr $\alpha=3$. Then the default event is equivalent to lapse (with no mortality payoff). It has been observed that insurance subscribers do not lapse optimally, which explains the use of the uncertain lapse model with minimum and maximum lapse rates $\underline{\lambda}$, $\overline{\lambda}$. 

<b>(a).</b> If insurance subscribers were to lapse optimally, i.e., exercise optimally their option to lapse, how would you price the contract?

<b>(b).</b> Explain how you can get this price (from optimal exercise) in the uncertain lapse model. Reuse the code provided in Question 3 to show your result (you may have to change some parameters in the code).

<b>(c).</b> Implement Longstaff-Schwartz algorithm to price the American option with payoff $u^D=0$ (Always perform a second indepedent run to get a clean lower bound price). Compare the price from uncertain lapse model in part (b) with the American price.

<b style="color:purple">Question a</b>  how  to price the contract?

If insurance subscribers were to lapse optimally, the pricing of the contract would be analogous to valuing an American-style option, where the policyholder has the right to terminate the contract at any time in order to maximize their financial gain.


The policyholder faces an optimal stopping problem: they decide whether to continue the contract or lapse, depending on whether the continuation value of the contract is greater than the immediate lapse value.
This is similar to pricing an American put option, where the policyholder compares the intrinsic value (the immediate lapse value) with the expected future value of holding the contract.

<b style="color:purple">Question b</b>  price (from optimal exercise) in the uncertain lapse model

we can get this price by setting $\lambda min=0 ,\lambda max=\infty$

In [365]:
lambda_min=0
lambda_max=10000
alpha=3
princing_longstaff(alpha/12)

72.27450600695923

<b style="color:purple">Question c</b>  Longstaff-Schwartz algorithm to price the American option with payoff $u^D=0$

Lets use a polynomial interpolation

In [50]:
alpha

0.25

In [ ]:
payoff = np.maximum(K-paths[-1], 0)
for i in range(len(ts)-2, 0, -1):
    discount = np.exp(-r*(ts[i+1]-ts[i]))
    payoff = payoff*discount
    p = np.polyfit(paths[i], payoff, deg=2) #on regresee S{t-1} sur exp(-rt)*(K-St)+
    contval = np.polyval(p, paths[i]) #continuation
    exerval = np.maximum(K-paths[i], 0) #exercice
    # identify the paths where we should exercise
    ind = exerval > contval
    payoff[ind] = exerval[ind]
np.mean(payoff*np.exp(-r*(ts[1]-ts[0])))

In [56]:
u_D(9)

0

In [57]:
# lets code de longtaff scwartz algorithm
K_D=0
npaths = 5000
paths = blackscholes_mc(S=S, vol=vol, r=0, q=0, ts=ts, npaths=npaths)
betas = np.zeros((len(ts), 5))
dt=1
payoff = u_mat(paths[-1])
for i in range(len(ts)-1,-1,-1):
    payoff=payoff-alpha/12*dt*i
    betas[i]=np.polyfit(paths[i], payoff, deg=4)
    contval=np.polyval(betas[i],paths[i])
    exerval=u_D(payoff)
    ind=exerval>contval
    payoff[ind]=exerval[ind]

npaths = 50000
paths = blackscholes_mc(S=S, vol=vol, r=0, q=0, ts=ts, npaths=npaths)
payoff = u_mat(paths[-1])
for i in range(len(ts)-1,-1,-1):
    payoff=payoff-(alpha/12)*dt*i
    contval=np.polyval(betas[i],paths[i])
    exerval=u_D(payoff)
    ind=exerval>contval
    payoff[ind]=exerval[ind]

print(np.mean(payoff))

C:\Users\tahab\AppData\Local\Temp\ipykernel_86800\1448587502.py:10: RankWarning: Polyfit may be poorly conditioned
  betas[i]=np.polyfit(paths[i], payoff, deg=4)


0.014194028430224274


In [48]:
# lets code de longtaff scwartz algorithm
K_D=0
npaths = 5000
paths = blackscholes_mc(S=S, vol=vol, r=0, q=0, ts=ts, npaths=npaths)
betas = np.zeros((len(ts), 2))
dt=1
payoff = u_mat(paths[-1])
for i in range(len(ts)-1,-1,-1):
    payoff=payoff-alpha/12*dt*i
    Z = blackscholes_price(K, ts[-1]-ts[i], paths[i], vol, callput='put')
    A = np.vstack((np.ones_like(Z), Z)).T
    betas[i] = np.linalg.lstsq(A, payoff, rcond=None)[0]
    contval=betas[i, 0]+betas[i, 1]*Z
    exerval=u_D(payoff)
    ind=exerval>contval
    payoff[ind]=exerval[ind]

npaths = 50000
paths = blackscholes_mc(S=S, vol=vol, r=0, q=0, ts=ts, npaths=npaths)
payoff = u_mat(paths[-1])
for i in range(len(ts)-1,-1,-1):
    #(payoff[0])
    payoff=payoff-(alpha/12)*dt*i
    Z = blackscholes_price(K, ts[-1]-ts[i], paths[i], vol, callput='put')
    contval=betas[i, 0]+betas[i, 1]*Z
    exerval=u_D(payoff)
    ind=exerval>contval
    payoff[ind]=exerval[ind]

print(np.mean(payoff))

C:\Users\tahab\AppData\Local\Temp\ipykernel_86800\1904069175.py:64: RuntimeWarning: divide by zero encountered in divide
  d1 = np.log(F/K)/v + 0.5*v


0.017722317902059744


In [49]:
np.mean(payoff)

0.017722317902059744